# Generated by Django 4.2.4 on 2023-10-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=500)),
                ('fecha_y_hora', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
