# Generated by Django 4.2.4 on 2023-10-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=100)),
                ('año', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='autenticacion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmedAPP.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.alumno')),
                ('curso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmedAPP.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmedAPP.horario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.profesor'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autenticacion.alumno')),
                ('curso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmedAPP.curso')),
            ],
        ),
    ]
